version: "2"
services:
  hermes:
    build: ./
    links:
      - mariadb
    environment:
      FLASK_ENV: production
    ports:
      - "5000:5000"

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: hermes
      MYSQL_DATABASE: hermes
      MYSQL_USER: hermes
      MYSQL_PASSWORD: hermes
    restart: on-failure
